name: Gitleaks Secret Scan

on:
  push:
##    branches: [ "main" ]
  pull_request:
##    branches: [ "main" ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Organization repo면 필요
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          # 커스텀 설정 쓰고 싶으면 (예시)
          # GITLEAKS_CONFIG: .github/gitleaks.toml
          # SARIF 업로드 끄고 싶으면
          # GITLEAKS_ENABLE_UPLOAD_ARTIFACT: "false"
